"""Generic script.mako for Alembic migrations (minimal placeholder).
This file is invoked by alembic when autogenerating migrations.
"""
% from alembic import op
% from sqlalchemy import *

"""
Do not edit this file unless you know what you're doing.
"""

revision = '<%revision%>'
down_revision = <%down_revision%>
branch_labels = None
depends_on = None

def upgrade():
    pass


def downgrade():
    pass
